query getCreditTokens($where: CreditToken_filter) {
  creditTokens(where: $where, first: 1000) {
    ...CreditTokenFragment
  }
}

query getCreditBalances($where: CreditBalance_filter) {
  creditBalances(where: $where, first: 1000) {
    account {
      id
    }
    credit {
      ...CreditTokenFragment
    }
    balance
  }
}
