fragment CreditTokenFragment on CreditToken {
  id
  creditTokenId
  creditId
  chainId
  decimals
  totalSupply
  totalSupplyTonnes
  factoryAddress
  registry {
    id
  }
  registryProjectId
  vintage
  tokenId
  tokenAddress
  project {
    projectId
    metadata {
      name
    }
  }
  provenanceKey
}
