fragment TokenFragment on Token {
  id
  symbol
  address
  totalSupply
  totalAmountLocked
  totalAmountAllocated
  priceUsdc {
    priceUsdc
  }
}

fragment MidnightInfoFragment on MidnightInfo {
  midnightIndex
  maturityId
  lastUpdated
  keeperUpdated

  k2YieldAccumulatorForK2
  k2YieldAccumulatorForKVCM_K2_LP
  k2YieldAccumulatorForKVCM

  riskyYieldAccumulatorForKVCM_K2_LP
  riskyYieldAccumulatorForKVCM_USDC_LP
  riskyYieldAccumulatorForK2

  syntheticYieldPps
  syntheticYieldTotalShares
  timestamp
}

fragment MidnightInfoWithPreviousMidnightInfoFragment on MidnightInfo {
  ...MidnightInfoFragment
  previousMidnightInfo {
    ...MidnightInfoFragment
  }
}

fragment LockActionFragment on LockAction {
  type
  amount

  yieldCutoffMidnightIndex

  k2YieldShares
  k2YieldPending
  k2YieldEntryMidnightInfo {
    ...MidnightInfoFragment
  }

  riskyYieldShares
  riskyYieldPending
  riskyYieldEntryMidnightInfo {
    ...MidnightInfoFragment
  }

  syntheticYieldEntryMidnightInfo {
    ...MidnightInfoFragment
  }

  timestamp
}
