query getCarbonClasses($where: CarbonClass_filter) {
  carbonClasses(where: $where, first: 1000) {
    priceUsdcPerTon {
      priceUsdc
    }
    id
    carbonClassId
    isRegistered
    registeredCredits(first: 1000) {
      creditTokenId
    }
  }
}

query getTokens {
  tokens(first: 1000) {
    ...TokenFragment
  }
}

query getTokenSnapshots($where: TokenSnapshot_filter) {
  tokenSnapshots(
    where: $where
    orderBy: hoursSinceEpoch
    orderDirection: desc
    first: 1
  ) {
    hoursSinceEpoch
    tokenAddress
    priceUsdc
    symbol
    supply
    totalAmountLocked
    totalAmountAllocated
  }
}

query getProtocolState {
  protocolStates(first: 1) {
    protocolStartTimestamp
    firstActiveMaturityId
    lastActiveMaturityId
    systemPauseStatus
    kvcmStakingPauseStatus
    k2StakingPauseStatus
    lpStakingPauseStatus
  }
}

query getMaturities($where: Maturity_filter) {
  maturities(where: $where, orderBy: maturityId, first: 1000) {
    timestamp
    maturityId

    syntheticYieldDiscountFactor
    syntheticYieldZeroCouponYieldCurve
    syntheticYieldUnscaledBondIssue

    riskyYieldDiscountFactor
    riskyYieldZeroCouponYieldCurve
    riskyYieldUnscaledBondIssue

    maturityMidnightInfo {
      ...MidnightInfoFragment
    }
  }
}

query getPrices {
  prices(first: 1000) {
    symbol
    priceUsdc
    tokenAddress
  }
}

query getAllocations($where: Allocation_filter) {
  allocations(where: $where) {
    id
    account {
      id
    }
    carbonClass {
      id
      priceUsdcPerTon {
        priceUsdc
      }
    }
    token {
      ...TokenFragment
    }
    amount
  }
}

query getLocks($where: Lock_filter) {
  locks(where: $where) {
    id
    type
    amount
    maturityId
    maturity {
      timestamp
      maturityMidnightInfo {
        ...MidnightInfoWithPreviousMidnightInfoFragment
      }
    }
    account {
      id
    }
    token {
      ...TokenFragment
    }

    # K2 lock specific field
    k2YieldClaimableAmount
    riskyYieldClaimableAmount
    yieldCutoffMidnightIndex

    # K2 yield field
    k2YieldShares
    k2YieldPending
    k2YieldEntryMidnightInfo {
      ...MidnightInfoFragment
    }
    k2YieldClaimed

    # Risky yield
    riskyYieldShares
    riskyYieldPending
    riskyYieldEntryMidnightInfo {
      ...MidnightInfoFragment
    }
    riskyYieldClaimed

    # Synthetic yield
    syntheticYieldShares
    syntheticYieldEntryMidnightInfo {
      ...MidnightInfoFragment
    }
    syntheticYieldClaimed
  }
}

query getAccountBalances($where: AccountBalance_filter) {
  accountBalances(where: $where) {
    account {
      id
    }
    token {
      ...TokenFragment
    }
    amount
  }
}

query getLatestMidnightInfo {
  midnightInfos(orderBy: midnightIndex, orderDirection: desc, first: 41) {
    ...MidnightInfoWithPreviousMidnightInfoFragment
  }
}
