fragment CarbonClassFragment on CarbonClass {
  id
  isRegistered
  priceUsdcPerTon {
    priceUsdc
  }
}

fragment TokenFragment on Token {
  id
  address
  priceUsdc {
    priceUsdc
  }
  symbol
  totalSupply
  totalAmountLocked
}
