query getCarbonClasses {
  carbonClasses {
    ...CarbonClassFragment
  }
}

query getTokens {
  tokens {
    ...TokenFragment
  }
}

query getTokenSnapshots($daysSinceEpoch: BigInt) {
  tokenSnapshots(where: { daysSinceEpoch: $daysSinceEpoch }) {
    daysSinceEpoch
    tokenAddress
    priceUsdc
    symbol
    supply
    totalAmountLocked
  }
}

query getMaturityManager {
  maturityManagers {
    id
    firstActiveMaturityId
    lastActiveMaturityId
  }
}

query getYieldBuckets($where: YieldBucket_filter) {
  yieldBuckets(where: $where, orderBy: maturityId) {
    bucketId
    maturityId
    multiplier
    zeroCouponYieldCurve
    discountFactor
    unscaledBondIssue
    maturity {
      timestamp
    }
  }
}
