const abi = [
  { inputs: [], name: 'InvalidAmountReceived', type: 'error' },
  { inputs: [], name: 'InvalidAmout', type: 'error' },
  { inputs: [], name: 'InvalidBeneficiaryLocation', type: 'error' },
  { inputs: [], name: 'InvalidCountryCode', type: 'error' },
  { inputs: [], name: 'InvalidPeriodEnd', type: 'error' },
  { inputs: [], name: 'InvalidPeriodStart', type: 'error' },
  { inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'token', type: 'address' }],
    name: 'SafeERC20FailedOperation',
    type: 'error',
  },
  { inputs: [], name: 'TokenNotSupported', type: 'error' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'enum LibRetire.CarbonBridge',
        name: 'carbonBridge',
        type: 'uint8',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'retiringAddress',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'retiringEntityString',
        type: 'string',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'beneficiaryAddress',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'beneficiaryString',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'retirementMessage',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'carbonToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'batchId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'enum IRetirementEvents.HasId',
        name: 'hasId',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'retiredAmount',
        type: 'uint256',
      },
    ],
    name: 'AggregatorRetired',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address', name: 'creditToken', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'address', name: 'inputTokenAddress', type: 'address' },
      { internalType: 'address', name: 'carbonClass', type: 'address' },
      { internalType: 'uint256', name: 'couponTonnes', type: 'uint256' },
    ],
    name: 'quoteRetireCreditViaKlima',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'creditToken', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'uint256', name: 'batchId', type: 'uint256' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      {
        components: [
          { internalType: 'address', name: 'retiringAddress', type: 'address' },
          {
            internalType: 'string',
            name: 'retiringEntityString',
            type: 'string',
          },
          {
            internalType: 'address',
            name: 'beneficiaryAddress',
            type: 'address',
          },
          { internalType: 'string', name: 'beneficiaryString', type: 'string' },
          { internalType: 'string', name: 'retirementMessage', type: 'string' },
          {
            internalType: 'string',
            name: 'beneficiaryLocation',
            type: 'string',
          },
          {
            internalType: 'string',
            name: 'consumptionCountryCode',
            type: 'string',
          },
          {
            internalType: 'uint256',
            name: 'consumptionPeriodStart',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'consumptionPeriodEnd',
            type: 'uint256',
          },
        ],
        internalType: 'struct LibRetire.RetireDetails',
        name: 'details',
        type: 'tuple',
      },
    ],
    name: 'retireCredit',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'creditToken', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'uint256', name: 'batchId', type: 'uint256' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'address', name: 'inputTokenAddress', type: 'address' },
      { internalType: 'address', name: 'carbonClass', type: 'address' },
      { internalType: 'uint256', name: 'maxInputTokenIn', type: 'uint256' },
      { internalType: 'uint256', name: 'couponTonnes', type: 'uint256' },
      {
        components: [
          { internalType: 'address', name: 'retiringAddress', type: 'address' },
          {
            internalType: 'string',
            name: 'retiringEntityString',
            type: 'string',
          },
          {
            internalType: 'address',
            name: 'beneficiaryAddress',
            type: 'address',
          },
          { internalType: 'string', name: 'beneficiaryString', type: 'string' },
          { internalType: 'string', name: 'retirementMessage', type: 'string' },
          {
            internalType: 'string',
            name: 'beneficiaryLocation',
            type: 'string',
          },
          {
            internalType: 'string',
            name: 'consumptionCountryCode',
            type: 'string',
          },
          {
            internalType: 'uint256',
            name: 'consumptionPeriodStart',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'consumptionPeriodEnd',
            type: 'uint256',
          },
        ],
        internalType: 'struct LibRetire.RetireDetails',
        name: 'details',
        type: 'tuple',
      },
    ],
    name: 'retireCreditViaKlima',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;

export default abi;
