name: Continuous integration

on:
  pull_request:
    branches: '*'

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    env:
      GOLDSKY_API_KEY: ${{ secrets.GOLDSKY_API_KEY }}
    strategy:
      fail-fast: false
      matrix:
        job: [knip, lint, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create node_modules directory # Or else action/cache fails silently
        run: mkdir -p node_modules

      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Set up Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '21.6.1' # Pin version to avoid breaking changes in node_modules
          cache: 'npm'

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit == 'true'
        run: npm run postinstall

      - name: Run ${{ matrix.job }}
        run: npm run ${{ matrix.job }}
