name: Continuous integration

on:
  pull_request:
    branches: '*'

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    env:
      GOLDSKY_API_KEY: ${{ secrets.GOLDSKY_API_KEY }}
      BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
      BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
    strategy:
      fail-fast: false
      matrix:
        job: [knip, lint, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '22.21.1' # Pin version to avoid breaking changes in node_modules
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run code generation
        run: pnpm run codegen

      - name: Run ${{ matrix.job }}
        run: pnpm run ${{ matrix.job }}
