name: Merge Staging to Main

on:
  workflow_dispatch:
  schedule:
    # At 15:30 UTC (8.30am PDT) Monday, Tuesday, Wednesday, and Thursday
    - cron: '30 15 * * 1,2,3,4'
jobs:
  test-staging:
    runs-on: ubuntu-latest
    env:
      GOLDSKY_API_KEY: ${{ secrets.GOLDSKY_API_KEY }}
      BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
      BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '22.21.1' # Pin version to avoid breaking changes in node_modules
          cache: 'pnpm'

      - name: Run build on staging
        run: |
          pnpm install
          pnpm run codegen
          pnpm run build

  merge-staging-to-main:
    needs: test-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge staging -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
